### PR TITLE
Fix build, add Dockerfile

### PR DESCRIPTION
**Pull request by runejuhl**
Note that building the Docker image using the `Dockerfile` requires https://github.com/summitto/pgp-packet-library/pull/60 to be merged.

### CODE REVIEW

**Comment by rockhouse** [comment]
Hi @runejuhl, as you can see the actions fail. Unfortunately we think this is connected to the ulimit as can be seen discussed here already https://github.com/summitto/pgp-key-generation/issues/42 
We tried to set that limit but github actions does not allow that. We dont know how to solve this issue at the moment please feel free to have a look. One more thing not sure why the Dockerfile is needed actually.

**Comment by runejuhl** [comment]
Hi @rockhouse. You're spot on about ulimit -- I tried running the tests in Docker locally, which also defaults to `64k`, and it fails in the same fashion. Running the tests in Docker with `--ulimit memlock:5000000:5000000` added on the command line makes the test work just fine.

The only thing I can think of off the top of my head is to introduce a way of toggling the memory lock when building the key generation program. Of course that will mean that there's a slight difference between what's run in CI and what's run in production, but compared to all CI tests failing I'd say it's a minor issue. Introducing a footgun like that isn't very nice, but I can't see any other simple ways of fixing the tests.

As for the `Dockerfile`: no, you're right, it's not required. I just prefer to build and experiment with foreign software in Docker -- that way I don't have to pollute my system with weird compilers and libraries 🙂 I'd be happy to remove the `Dockerfile` or move it to another PR if you'd prefer that instead.

**Comment by rockhouse** [comment]
So I've managed to increase the ulimit, now the tests pass https://github.com/summitto/pgp-key-generation/actions/runs/3163357384 . We can merge yours (after update) or mine(https://github.com/summitto/pgp-key-generation/pull/59), just let me know your preference.

**Comment by runejuhl** [comment]
Huh, what a simple solution 🤦 😁 

We talked about the `Dockerfile` before -- let me know if you want me to remove it. Otherwise I think this PR is good to go now 👍

**Review by rockhouse — APPROVED** [review]
LGTM

**Pull request merged**
